---
output: 
  datadrivencv::cv:
    keep_tex: yes

header-includes:
- "\\usepackage{hyperref}"
- "\\usepackage{array}" # for the table format
  
geometry: margin=1in

title: "CV"
author: Eirik Berger Abel

jobtitle: "PhD Research Scholar | Norwegian School of Economics"
#address: "Helleveien 30, 5045 Bergen, Vestlandet, Norway"
fontawesome: yes
email: eirik.berger@gmail.com
#github: eirikberger
#twitter: eirikberger
phone: "+47 954 61 029"
#web: eirikberger.github.io
updated: TRUE
rdateformat: "`r format(Sys.time(), '%d %b %Y')`"

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe

# Read in all data and initialize a CV printer object
CV <- datadrivencv::create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1bBlRkTPyPXkxHUzBo7H6xJm33vnP-qv0sJ5rI1eCRO4/edit?usp=sharing"
)

```


<!-- \textbf{Placement Director:} -->
<!-- Katrine V. L\o ken | -->
<!-- \textit{Phone:} +47 416 615 91 | -->
<!-- \textit{E-mail:} \href{mailto:katrine.loken@nhh.no}{katrine.loken@nhh.no} -->

<!-- \vspace{2mm} -->
<!-- \hrule -->
<!-- \vspace{2mm} -->


```{r, education}
CV %>% datadrivencv::print_section('education', regex_expression = '{title} at {institution} \\hfill {timeline}', title = '# Education')
```

```{r, visits}
CV %>% datadrivencv::print_section('visits', regex_expression = '{title} at {institution} ({description_bullets}) \\hfill {timeline}', title = '# Visiting Activities')
```

# Research Fields

\vspace{-1mm}
\begin{tabular}{p{.85in}>{\hangindent=1em}p{5.65in}<{\raggedright}}
Primary:   & Labor Economics and Applied Microeconomics\\
Secondary: & Economic History\\
\end{tabular}
\vspace{-1mm}

# References

\begin{tabular}{p{2.15in}>{\hangindent=1em}p{2.15in}>{\hangindent=1em}p{2.15in}<{\raggedright}}
\textbf{Prof. Kjell Gunnar Salvanes}   & \textbf{Prof. Aline Bütikofer} &  \textbf{Prof. Ran Abramitzky}\\
Norwegian School of Economics & Norwegian School of Economics & Stanford University\\
\href{mailto:Kjell.Salvanes@nhh.no}{Kjell.Salvanes@nhh.no} \vspace{2mm} & \href{mailto:Aline.Buetikofer@nhh.no}{Aline.Buetikofer@nhh.no} \vspace{2mm} & \href{mailto:RanAbr@stanford.edu}{RanAbr@stanford.edu}\\
\end{tabular}

<!-- # Placement Director -->

<!-- \begin{tabular}{p{2.15in}>{\hangindent=1em}p{2.15in}>{\hangindent=1em}p{2.15in}<{\raggedright}} -->
<!-- \textbf{Prof. Katrine V. L\o ken}\\ -->
<!-- Norwegian School of Economics\\ -->
<!-- \href{mailto:Katrine.Loken@nhh.no}{Katrine.Loken@nhh.no}\\ -->
<!-- \end{tabular} -->


```{r, articles}
CV %>% datadrivencv::print_section('articles', regex_expression = '{title}, *{loc}*, {description_bullets} \\hfill {start}', title = '# Journal Articles')
```

```{r, working_papers}
CV %>% datadrivencv::print_section('working_papers', regex_expression = '"**{title}" {description_bullets} \\hfill {start}**

                                                                       {abstract}', title = '# Working Papers')
```

<!-- # ```{r, working_papers} -->
<!-- # CV %>% datadrivencv::print_section('working_papers', regex_expression = '"{title}" {description_bullets} \\hfill {start}', title = '# Working Papers') -->
<!-- # ``` -->

```{r, ongoing_work}
CV %>% datadrivencv::print_section('ongoing_work', regex_expression = '"{title}" {description_bullets}', title = '# Selected Work in Progress')
```

```{r, not_for_publishing}
CV %>% datadrivencv::print_section('not_for_publishing', regex_expression = '"{title}", {loc}, {description_bullets} \\hfill {start}', title = '# Articles Not Intended for Publication')
```

```{r, other}
CV %>% datadrivencv::print_section('other', regex_expression = '{title} at {institution} \\hfill {timeline}', title = '# Other Engagements')
```

```{r, seminars}
CV %>% datadrivencv::print_section('seminar', regex_expression = '{title} \\hfill {start}', title = '# Presentations')
```

```{r, proff}
CV %>% datadrivencv::print_section('proff', regex_expression = '{title}', title = '# Refereeing')
```

```{r, teaching}
CV %>% datadrivencv::print_section('teaching', regex_expression = '{title} \\hfill {start}', title = '# Teaching and Research Assistance \n## Teaching Assistant')
```

```{r, RA}
CV %>% datadrivencv::print_section('RA', regex_expression = '{title} \\hfill {end}', title = '## Research Assistant')
```

```{r, skills_data}
CV %>% datadrivencv::print_section('data_science', regex_expression = '{title}', title = '# Skills \n## Data science')
```

```{r, skills_language}
CV %>% datadrivencv::print_section('language', regex_expression = '{title}', title = '\\vspace{-0.3cm}## Languages')
```


